import AuthSession from '@/component/AuthSession';
import Nav from '@/component/Nav';
import '@/scss/style.scss';

export const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body>
				<AuthSession>
					<div id='wrap'>
						<Nav />
						<main>
							<section id='list'>{children}</section>
						</main>
					</div>
				</AuthSession>
			</body>
		</html>
	);
}
