export const metadata = {
	title: '게시판',
	description: 'Generated by egoing',
};

export default async function BoardLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return <>{children}</>;
}
